"""redesign interview schedule

Revision ID: b41385f5cd3b
Revises: b98c92434ec4
Create Date: 2026-06-24 11:23:54.194111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41385f5cd3b'
down_revision = 'b98c92434ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['application_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])
        batch_op.drop_column('drive_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'placement_drives', ['drive_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###
