"""Added application uniqueness constraint

Revision ID: e3ee2574c02e
Revises: 59fd35cb5eda
Create Date: 2026-06-14 19:10:48.638058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ee2574c02e'
down_revision = '59fd35cb5eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_student_drive', ['student_id', 'drive_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_drive', type_='unique')

    # ### end Alembic commands ###
